# Site settings
title: BilgehanDental | Bilgehan Dental
description: "Bilgehan Dental."
baseurl: "/bilgehandental" # the subpath of your site, e.g. /blog
url: "https://19pro.github.io/bilgehandental" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: BilgehanDental
    hero_description: Bilgehan Dental.

# Contact form: 1fe975b79a805db5f31fc4f74526f328
api_token: bf03ed7e99824273d92798b4ae4a63fa # Enter API token here

# Contact info
contact:
    phone: 932 50 540
    emergency: 931 53 234
    email: contact@bilgehandental.com
    address: Atakum, <br> Samsun

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Atakum, Samsun
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2017 BilgehanDental - Tüm hakları saklıdır

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
